# 테스트를 돌릴 때... my sql 은 local 을 쓰고 (더미 데이터라서 docker 3307 말고 다른데 저장하기)
# redis 도 따로 만들어서 돌려야해요 6378

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tixy?rewriteBatchedStatements=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6378

  logging:
    level:
      org.springframework.cache: TRACE
      org.springframework.data.redis: DEBUG
      io.lettuce.core: DEBUG

JWT_SECRET_KEY: testsecretkeyfortestjwthellotakocuteverymuch1234567890